apis:
  testapi:
    base_url: "https://jsonplaceholder.typicode.com"
    auth_type: "none"
    endpoints:
      get_posts:
        path: "/posts"
        method: "GET"
        pagination:
          type: "none"
      get_post:
        path: "/posts/{{.FIRST_ID}}"
        method: "GET"
        pagination:
          type: "none"
auth:
  default: "none"
  credentials: {}
retry:
  max_attempts: 3
  backoff_seconds: 2
  exclude_errors: [401, 403]
logging:
  level: "debug"
chain:
  variables: {}
  steps:
    - name: list_posts
      request:
        api: "testapi"
        endpoint: "get_posts"
        method: "GET"
      extract:
        FIRST_ID: ".[0].id"
    - name: get_post
      request:
        api: "testapi"
        endpoint: "get_post"
        method: "GET"
